name: Sync with upstream
on:
  schedule:
    - cron: "30 22 * * *"
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: LSPosed/MagiskOnWSALocal    # set the upstream repo
          upstream-branch: main   # set the upstream branch to merge from
          branch: main          # set the branch to merge to
          token: ${{ secrets.GITHUB_TOKEN }}  # set the token to push to the repo

      - name: Create telegram alert for failure on scheduled run
        if: failure() && github.event_name == 'schedule'
        uses: appleboy/telegram-action@master 
        with: 
          to: ${{ secrets.TELEGRAM_TO }}  # set the telegram chat id
          token: ${{ secrets.TELEGRAM_TOKEN }}  # set the telegram bot token
          message: |  # set the message
            Merge upstream failed
            Origin: https://github.com/${{ github.repository }}
            Upstream: https://github.com/LSPosed/MagiskOnWSALocal